In [2]:
import numpy as np

## Creating ndarray

In [3]:

# From a list
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1, type(arr1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
# From a tuple
arr2 = np.array((1, 2, 3, 4, 5))

print(arr2)

[1 2 3 4 5]


In [5]:
# From 2D list
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr3)

[[1 2 3]
 [4 5 6]]


## Generating ndarray

In [6]:
# From 0 to 9
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# From 1 to 10 with step of 2
arr = np.arange(1, 10, 2)

print(arr)

[1 3 5 7 9]


In [8]:
arr = np.linspace(0, 1, 5)

print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
arr = np.random.rand(3, 2)  # 3x2 array with random values
print(arr)

[[0.34890426 0.36023839]
 [0.95585553 0.04770949]
 [0.85395127 0.94599605]]


In [10]:
arr = np.random.randn(3, 2)  # 3x2 array with random values
print(arr)

[[ 0.15366602 -1.7437933 ]
 [ 0.2525554   0.54003707]
 [-2.51460888 -0.60071118]]


In [11]:
arr = np.zeros((3, 2))  # 2D array with shape (3, 4)
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
arr = np.ones((3, 2))  # 2D array with shape (3, 4)
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
arr = np.eye(3)  # 3x3 identity matrix
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
arr = np.identity(3) 
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Getting information

In [17]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2, 3]], [[4, 5, 6]]])

In [19]:
#checking the rank
arr_2d.ndim

2

In [20]:
arr_3d.ndim

3

In [21]:
#checking shape
arr_2d.shape

(2, 3)

In [22]:
arr_3d.shape

(2, 1, 3)

In [23]:
#get number of values
arr_2d.size

6

In [24]:
arr_3d.size

6

In [27]:
# get data type
arr_2d.dtype

dtype('int64')

In [28]:
arr_3d.dtype

dtype('int64')

## Selecting elements

In [30]:
#indexing

arr = np.array([1, 2, 3, 4])

arr[2]

3

In [31]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr[1, 2]

7

In [32]:
# slicing

arr = np.arange(10)

arr[1:4]

array([1, 2, 3])

In [33]:
# boolean indexing

arr[arr>5]

array([6, 7, 8, 9])

## Reshaping

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
#Transposing
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
#reshape

reshaped_arr = arr.reshape((1, 6))

In [49]:
arr.shape, reshaped_arr.shape

((2, 3), (1, 6))

## Elementwise operations

In [54]:
arr_1 = np.random.rand(3, 3)
arr_2 = np.ones((3, 3))

arr_1, arr_2

(array([[0.42774724, 0.66333092, 0.37008836],
        [0.83085536, 0.80249491, 0.66481621],
        [0.52534874, 0.77640806, 0.00943689]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [55]:
# adding

arr_1 + arr_2

array([[1.42774724, 1.66333092, 1.37008836],
       [1.83085536, 1.80249491, 1.66481621],
       [1.52534874, 1.77640806, 1.00943689]])

In [56]:
# subtracting

arr_1 - arr_2

array([[-0.57225276, -0.33666908, -0.62991164],
       [-0.16914464, -0.19750509, -0.33518379],
       [-0.47465126, -0.22359194, -0.99056311]])

In [57]:
# multiplying

arr_1 * arr_2

array([[0.42774724, 0.66333092, 0.37008836],
       [0.83085536, 0.80249491, 0.66481621],
       [0.52534874, 0.77640806, 0.00943689]])

In [59]:
# dividing

arr_2 / arr_1

array([[  2.33782921,   1.50754317,   2.70205743],
       [  1.20357893,   1.24611382,   1.50417512],
       [  1.90349747,   1.28798251, 105.9670912 ]])

In [60]:
# compare

arr_1 < arr_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [62]:
# broadcasting
arr_1 = np.zeros((3, 4))
arr_2 = np.array([1, 2, 3, 4])

arr_1 + arr_2

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [65]:
# multiply by scalar
arr_1 = np.ones((3, 4))
arr_1 * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [73]:
#raising to power
arr_1 = np.arange(5)
arr_1 ** 2

array([ 0,  1,  4,  9, 16])

## Aggregation

In [87]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
# sum

np.sum(arr_1)

21

In [89]:
# sum along axis

np.sum(arr_1, axis=1)

array([ 6, 15])

In [90]:
# sum along axis

np.sum(arr_1, axis=0)

array([5, 7, 9])

In [91]:
# smallest value

np.min(arr_1)

1

In [92]:
# biggest value

np.max(arr_1)

6

In [93]:
# mean

np.mean(arr_1)

3.5

In [94]:
# standard deviation

np.std(arr_1)

1.707825127659933

## Combining arrays

In [96]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6], [7, 8]])

arr_1, arr_2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [99]:
# horizontal stack

np.hstack((arr_1, arr_2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [100]:
# vertical stack

np.vstack((arr_1, arr_2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [102]:
# concatenate

np.concatenate((arr_1, arr_2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [103]:
np.concatenate((arr_1, arr_2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Linear Algebra

In [104]:
arr_1 = np.array([[4, 5], [6, 7]])
arr_2 = np.eye(2)

In [106]:
#Matrix multiplication

arr_1.dot(arr_2)

array([[4., 5.],
       [6., 7.]])

In [107]:
#Matrix multiplication

arr_1 @ arr_2

array([[4., 5.],
       [6., 7.]])

In [109]:
# Vector magnitude

arr_1 = np.arange(5)

np.linalg.norm(arr_1)

5.477225575051661

In [110]:
# Distance between vectors


arr_1 = np.array([1, 0])
arr_2 = np.array([0, 1])

np.linalg.norm(arr_1-arr_2)

1.4142135623730951

In [111]:
# cosine similarity

(arr_1/np.linalg.norm(arr_1)).dot((arr_2/np.linalg.norm(arr_2)))

0.0

## Saving and Loading

In [112]:
arr_1 = np.eye(10)

arr_1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [116]:
np.save("array.npy", arr_1)

In [117]:
np.load("array.npy")

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])